const object_device_Folder_definitions = {
	reloadAll: {
		type: 'state',
		common: {
			name: `reload All Tablet view`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
};

const object_main_definitions = {
	state_of_charge_vis: {
		type: 'state',
		common: {
			name: `State of charge for the Vis`,
			type: 'number',
			role: 'value.battery',
			max: 100,
			min: 0,
			def: 0,
			read: true,
			write: false,
			states: {
				0: 'leer',
				1: '10 %',
				2: 'charge 10 %',
				3: '20 %',
				4: 'charge 20 %',
				5: '30 %',
				6: 'charge 30 %',
				7: '40 %',
				8: 'charge 40 %',
				9: '50 %',
				10: 'charge 50 %',
				11: '60 %',
				12: 'charge 60 %',
				13: '70 %',
				14: 'charge 70 %',
				15: '80 %',
				16: 'charge 80 %',
				17: '90 %',
				18: 'charge 90 %',
				19: '100 %',
				20: 'charge 100 %',
			},
		},
		native: {},
	},
	manualBrightness: {
		type: 'state',
		common: {
			name: `manual Brightness in percent`,
			type: 'number',
			role: 'level.dimmer',
			unit: '%',
			max: 100,
			min: 0,
			def: 0,
			read: true,
			write: true,
		},
		native: {},
	},
	brightness_control_mode: {
		type: 'state',
		common: {
			name: `brightness control mode`,
			type: 'boolean',
			role: 'switch',
			def: false,
			read: true,
			write: true,
			states: {
				false: 'Admin',
				true: 'User',
			},
		},
		native: {},
	},
	brightness: {
		type: 'state',
		common: {
			name: `brightness from the Device`,
			type: 'number',
			role: 'level.dimmer',
			max: 255,
			min: 0,
			def: 0,
			read: true,
			write: false,
		},
		native: {},
	},
	battery: {
		type: 'state',
		common: {
			name: `battery in percent`,
			type: 'number',
			role: 'battery.percent',
			max: 100,
			min: 0,
			def: 0,
			unit: '%',
			read: true,
			write: false,
		},
		native: {},
	},
	lastInfoUpdate: {
		type: 'state',
		common: {
			name: `Date/Time of last information update from Fully Browser`,
			type: 'number',
			role: 'value.time',
			read: true,
			write: false,
		},
		native: {},
	},
	charging_warning: {
		type: 'state',
		common: {
			name: ` charging warning`,
			type: 'boolean',
			role: 'info',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	isFullyAlive: {
		type: 'state',
		common: {
			name: `Is Fully Browser Alive?`,
			type: 'boolean',
			role: 'info',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
};

const object_commands_definitions = {
	startURL: {
		type: 'state',
		common: {
			name: `set the startURL`,
			type: 'string',
			role: 'text.url',
			def: '',
			read: true,
			write: true,
		},
		native: {},
	},
	camshot: {
		type: 'state',
		common: {
			name: `makes a camshot image`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	motionDetection: {
		type: 'state',
		common: {
			name: `turn motion detection on and off `,
			type: 'boolean',
			role: 'switch',
			def: false,
			read: true,
			write: true,
		},
		native: {},
	},
	loadStartURL: {
		type: 'state',
		common: {
			name: `loadStartURL`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	clearCache: {
		type: 'state',
		common: {
			name: `clearCache`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	clearWebstorage: {
		type: 'state',
		common: {
			name: `clearWebstorage`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	clearCookies: {
		type: 'state',
		common: {
			name: `clearCookies`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	restartApp: {
		type: 'state',
		common: {
			name: `restartApp`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	exitApp: {
		type: 'state',
		common: {
			name: `exitApp`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	screenOn: {
		type: 'state',
		common: {
			name: `screenOn`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	screenOff: {
		type: 'state',
		common: {
			name: `screenOff`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	forceSleep: {
		type: 'state',
		common: {
			name: `forceSleep`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	triggerMotion: {
		type: 'state',
		common: {
			name: `triggerMotion`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	startScreensaver: {
		type: 'state',
		common: {
			name: `startScreensaver`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	stopScreensaver: {
		type: 'state',
		common: {
			name: `stopScreensaver`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	startDaydream: {
		type: 'state',
		common: {
			name: `startDaydream`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	stopDaydream: {
		type: 'state',
		common: {
			name: `stopDaydream`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	toForeground: {
		type: 'state',
		common: {
			name: `toForeground`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	popFragment: {
		type: 'state',
		common: {
			name: `popFragment`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	enableLockedMode: {
		type: 'state',
		common: {
			name: `enableLockedMode`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	disableLockedMode: {
		type: 'state',
		common: {
			name: `disableLockedMode`,
			type: 'boolean',
			role: 'button',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	startApplication: {
		type: 'state',
		common: {
			name: `startApplication`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: true,
		},
		native: {},
	},
	loadURL: {
		type: 'state',
		common: {
			name: `loadURL`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: true,
		},
		native: {},
	},
	textToSpeech: {
		type: 'state',
		common: {
			name: `textToSpeech`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: true,
		},
		native: {},
	},
	setStringSetting: {
		type: 'state',
		common: {
			name: `setStringSetting`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: true,
		},
		native: {},
	},
	mediaVolumen: {
		type: 'state',
		common: {
			name: `media Volumen`,
			type: 'number',
			role: 'level.volume',
			unit: '%',
			max: 100,
			min: 0,
			def: 0,
			read: true,
			write: true,
		},
		native: {},
	},
};

const object_device_info_definitions = {
	currentPage: {
		type: 'state',
		common: {
			name: `Shows the current page`,
			type: `string`,
			role: `url`,
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	camshot64: {
		type: 'state',
		common: {
			name: `camshot64 image in base64 format for HTML`,
			type: `string`,
			role: `text`,
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	camshotUrl: {
		type: 'state',
		common: {
			name: `Url für eine camshot aufnahme`,
			type: `string`,
			role: `text`,
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	batteryTemperature: {
		type: 'state',
		common: {
			name: `The temperature of the battery`,
			type: `number`,
			role: `value.temperature`,
			unit: `°C`,
			def: 0,
			read: true,
			write: false,
		},
		native: {},
	},
	isInScreensaver: {
		type: 'state',
		common: {
			name: `isInScreensaver`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	isScreenOn: {
		type: 'state',
		common: {
			name: `isScreenOn`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	kioskMode: {
		type: 'state',
		common: {
			name: `kioskMode`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	maintenanceMode: {
		type: 'state',
		common: {
			name: `maintenanceMode`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	isInDaydream: {
		type: 'state',
		common: {
			name: `isInDaydream`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	isLicensed: {
		type: 'state',
		common: {
			name: `isLicensed`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	plugged: {
		type: 'state',
		common: {
			name: `plugged`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	keyguardLocked: {
		type: 'state',
		common: {
			name: `keyguardLocked`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	isDeviceAdmin: {
		type: 'state',
		common: {
			name: `isDeviceAdmin`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	kioskLocked: {
		type: 'state',
		common: {
			name: `kioskLocked`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	isDeviceOwner: {
		type: 'state',
		common: {
			name: `isDeviceOwner`,
			type: 'boolean',
			role: 'indicator',
			def: false,
			read: true,
			write: false,
		},
		native: {},
	},
	wifiSignalLevel: {
		type: 'state',
		common: {
			name: `wifiSignalLevel`,
			type: 'number',
			role: 'value',
			def: 0,
			read: true,
			write: true,
		},
		native: {},
	},
	deviceName: {
		type: 'state',
		common: {
			name: `deviceName`,
			type: 'string',
			role: 'info.name',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	displayHeightPixels: {
		type: 'state',
		common: {
			name: `displayHeightPixels`,
			type: 'number',
			role: 'info.display',
			def: 0,
			unit: 'px',
			read: true,
			write: false,
		},
		native: {},
	},
	displayWidthPixels: {
		type: 'state',
		common: {
			name: `displayWidthPixels`,
			type: 'number',
			role: 'info.display',
			def: 0,
			unit: 'px',
			read: true,
			write: false,
		},
		native: {},
	},
	screenOrientation: {
		type: 'state',
		common: {
			name: `screenOrientation`,
			type: 'number',
			role: 'info.display',
			def: 0,
			read: true,
			write: false,
		},
		native: {},
	},
	ip6: {
		type: 'state',
		common: {
			name: `ip6`,
			type: 'string',
			role: 'info.ip',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	mac: {
		type: 'state',
		common: {
			name: `mac`,
			type: 'string',
			role: 'info.mac',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	appVersionName: {
		type: 'state',
		common: {
			name: `appVersionName`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	startUrl: {
		type: 'state',
		common: {
			name: `startUrl`,
			type: 'string',
			role: 'url',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	deviceManufacturer: {
		type: 'state',
		common: {
			name: `deviceManufacturer`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	androidVersion: {
		type: 'state',
		common: {
			name: `androidVersion`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	foregroundApp: {
		type: 'state',
		common: {
			name: `foregroundApp`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	LastAppStart: {
		type: 'state',
		common: {
			name: `Last App Start`,
			type: 'string',
			role: 'info',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	currentFragment: {
		type: 'state',
		common: {
			name: `currentFragment`,
			type: 'string',
			role: 'info',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	device_ip: {
		type: 'state',
		common: {
			name: `device ip`,
			type: 'string',
			def: '',
			role: 'info.ip',
			read: true,
			write: false,
		},
		native: {},
	},
	deviceModel: {
		type: 'state',
		common: {
			name: `device Model`,
			type: 'string',
			role: 'text',
			def: '',
			read: true,
			write: false,
		},
		native: {},
	},
	ssid: {
		type: 'state',
		common: {
			name: `Wlan ssid`,
			type: 'string',
			def: '',
			role: 'info',
			read: true,
			write: false,
		},
		native: {},
	},
};

const object_memory_definitions = {
	internalStorageFreeSpace: {
		type: 'state',
		common: {
			name: `internalStorageFreeSpace`,
			type: 'string',
			role: 'state',
			def: '0',
			read: true,
			write: false,
		},
		native: {},
	},
	appTotalMemory: {
		type: 'state',
		common: {
			name: `appTotalMemory`,
			type: 'string',
			role: 'state',
			def: '0',
			read: true,
			write: false,
		},
		native: {},
	},
	ramFreeMemory: {
		type: 'state',
		common: {
			name: `ramFreeMemory`,
			type: 'string',
			role: 'state',
			def: '0',
			read: true,
			write: false,
		},
		native: {},
	},
	appFreeMemory: {
		type: 'state',
		common: {
			name: `appFreeMemory`,
			type: 'string',
			role: 'state',
			def: '0',
			read: true,
			write: false,
		},
		native: {},
	},
	internalStorageTotalSpace: {
		type: 'state',
		common: {
			name: `internalStorageTotalSpace`,
			type: 'string',
			role: 'state',
			def: '0',
			read: true,
			write: false,
		},
		native: {},
	},
	ramUsedMemory: {
		type: 'state',
		common: {
			name: `ramUsedMemory`,
			type: 'string',
			role: 'state',
			def: '0',
			read: true,
			write: false,
		},
		native: {},
	},
	appUsedMemory: {
		type: 'state',
		common: {
			name: `appUsedMemory`,
			type: 'string',
			role: 'state',
			def: '0',
			read: true,
			write: false,
		},
		native: {},
	},
	ramTotalMemory: {
		type: 'state',
		common: {
			name: `ramTotalMemory`,
			type: 'string',
			role: 'state',
			def: '0',
			read: true,
			write: false,
		},
		native: {},
	},
};

const object_vis_View_definitions = {
	Timer_View_Switch: {
		type: 'state',
		common: {
			name: `Timer View Switch`,
			type: 'number',
			role: 'value',
			def: 0,
			read: true,
			write: false,
		},
		native: {},
	},
	widget_8_view: {
		type: 'state',
		common: {
			name: `widget 8 view`,
			type: 'number',
			role: 'value',
			def: 0,
			read: true,
			write: true,
		},
		native: {},
	},
};

const object_kiosk_definitions = {
	lockKiosk: {
		type: 'state',
		common: {
			name: `lock or unlock the Kiosk mode`,
			type: 'boolean',
			role: 'switch',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	kioskMode: {
		type: 'state',
		common: {
			name: `switch the kiosk mode on or off`,
			type: 'boolean',
			role: 'switch',
			def: false,
			read: true,
			write: true,
		},
		native: {},
	},
	kioskPin: {
		type: 'state',
		common: {
			name: `change of kioskPin`,
			type: 'string',
			role: 'state',
			def: '',
			read: true,
			write: true,
		},
		native: {},
	},
	kioskPin_confirm: {
		type: 'state',
		common: {
			name: `confirm the change of kioskPin`,
			type: 'string',
			role: 'state',
			def: '',
			read: true,
			write: true,
		},
		native: {},
	},
	disableVolumeButtons: {
		type: 'state',
		common: {
			name: `Lock volume buttons in Kiosk Mode (doesn't lock in other apps)`,
			type: 'boolean',
			role: 'switch',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	disablePowerButton: {
		type: 'state',
		common: {
			name: `Lock the power button in Kiosk Mode`,
			type: 'boolean',
			role: 'switch',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	disableHomeButton: {
		type: 'state',
		common: {
			name: `Lock the home button and auto-run Fully in Kiosk Mode on boot`,
			type: 'boolean',
			role: 'switch',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	disableStatusBar: {
		type: 'state',
		common: {
			name: `Lock status bar and system settings access`,
			type: 'boolean',
			role: 'switch',
			def: true,
			read: true,
			write: true,
		},
		native: {},
	},
	kioskExitGesture: {
		type: 'state',
		common: {
			name: `Select the gesture to show the PIN dialog`,
			type: 'number',
			role: 'switch',
			def: 0,
			read: true,
			write: true,
			states: {
				0: 'Swipe from Left or Long Press Back',
				1: 'Double Tap Top Left and Bottom Right Corner',
				2: 'Fast 5 Taps Anywhere',
			},
		},
		native: {},
	},
};

module.exports = {
	object_device_info_definitions,
	object_commands_definitions,
	object_vis_View_definitions,
	object_memory_definitions,
	object_device_Folder_definitions,
	object_main_definitions,
	object_kiosk_definitions,
};
