/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "active": {                                      "en": "Activate Telegram Warning",                       "de": "Aktivieren Sie die Telegrammwarnung",             "ru": "Активировать предупреждение Telegram",            "pt": "Ativar aviso de telegrama",                       "nl": "Activeer Telegram-waarschuwing",                  "fr": "Activer l'avertissement de télégramme",           "it": "Attiva l'avviso Telegram",                        "es": "Activar advertencia de telegrama",                "pl": "Aktywuj ostrzeżenie telegramu"},
    "addresses": {                                   "en": "Addresses to monitoring",                         "de": "Adresse für Monitoring",                          "ru": "Адреса к мониторингу",                            "pt": "Endereços para monitoramento",                    "nl": "Adressen voor monitoring",                        "fr": "Adresses de surveillance",                        "it": "Indirizzi per il monitoraggio",                   "es": "Direcciones para el monitoreo",                   "pl": "Adresy do monitorowania"},
    "charge": {                                      "en": "Data point from a charger",                       "de": "Datenpunkt von einem Ladegerät",                  "ru": "Точка данных от зарядного устройства",            "pt": "Ponto de dados de um carregador",                 "nl": "Datapunt van een oplader",                        "fr": "Point de données d'un chargeur",                  "it": "Punto dati da un caricabatterie",                 "es": "Punto de datos de un cargador",                   "pl": "Punkt danych z ładowarki"},
    "charger": {                                     "en": "Charger",                                         "de": "Ladegerät",                                       "ru": "зарядное устройство",                             "pt": "Carregador",                                      "nl": "Lader",                                           "fr": "Chargeur",                                        "it": "Caricabatterie",                                  "es": "Cargador",                                        "pl": "Ładowarka"},
    "delete": {                                      "en": "Delete",                                          "de": "löschen",                                         "ru": "удалять",                                         "pt": "Excluir",                                         "nl": "Verwijderen",                                     "fr": "Effacer",                                         "it": "Elimina",                                         "es": "Eliminar",                                        "pl": "Kasować"},
    "enabled": {                                     "en": "Enabled",                                         "de": "Aktiviert",                                       "ru": "Включено",                                        "pt": "ativado",                                         "nl": "Ingeschakeld",                                    "fr": "Activée",                                         "it": "Abilitato",                                       "es": "Habilitado",                                      "pl": "Włączone"},
    "interval": {                                    "en": "Polling interval[sec]",                           "de": "Abfrageintervall [Sek.]",                         "ru": "Интервал опроса [сек]",                           "pt": "Intervalo de pesquisa [seg]",                     "nl": "Polling-interval [sec]",                          "fr": "Intervalle d'interrogation [sec]",                "it": "Intervallo di polling [sec]",                     "es": "Intervalo de sondeo [seg]",                       "pl": "Interwał odpytywania [s]"},
    "ip": {                                          "en": "IP Address",                                      "de": "IP Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP"},
    "motionId": {                                    "en": "Data point from a motionsensor",                  "de": "Datenpunkt von einem Bewegungssensor",            "ru": "Точка данных от датчика движения",                "pt": "Ponto de dados de um sensor de movimento",        "nl": "Datapunt van een bewegingssensor",                "fr": "Point de données d'un capteur de mouvement",      "it": "Punto dati da un sensore di movimento",           "es": "Punto de datos de un sensor de movimiento",       "pl": "Punkt danych z czujnika ruchu"},
    "motionsensor": {                                "en": "Motionsensor",                                    "de": "Bewegungssensor Aktivieren",                      "ru": "Датчик движения",                                 "pt": "Sensor de movimento",                             "nl": "Bewegingssensor",                                 "fr": "Capteur de mouvement",                            "it": "Sensore di movimento",                            "es": "Sensor de movimiento",                            "pl": "Czujnik ruchu"},
    "name": {                                        "en": "Tablet name",                                     "de": "Tablet Name",                                     "ru": "Название планшета",                               "pt": "Nome do tablet",                                  "nl": "Tablet naam",                                     "fr": "Nom de la tablette",                              "it": "Nome del tablet",                                 "es": "Nombre de la tableta",                            "pl": "Nazwa tabletu"},
    "optional": {                                    "en": "Optional",                                        "de": "Optional",                                        "ru": "По желанию",                                      "pt": "Opcional",                                        "nl": "Optioneel",                                       "fr": "Optionnel",                                       "it": "Opzionale",                                       "es": "Opcional",                                        "pl": "Opcjonalny"},
    "polling interval": {                            "en": "Polling interval",                                "de": "Abrufintervall",                                  "ru": "Интервал опроса",                                 "pt": "Intervalo de pesquisa",                           "nl": "Polling-interval",                                "fr": "Intervalle d'interrogation",                      "it": "Intervallo di polling",                           "es": "Intervalo de votación",                           "pl": "Interwał odpytywania"},
    "port": {                                        "en": "port",                                            "de": "port",                                            "ru": "порт",                                            "pt": "porta",                                           "nl": "haven",                                           "fr": "Port",                                            "it": "porta",                                           "es": "Puerto",                                          "pl": "Port"},
    "psw": {                                         "en": "Password",                                        "de": "Password",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło"},
    "settings": {                                    "en": "Adapter settings",                                "de": "Adapter-Einstellungen",                           "ru": "Настройки адаптера",                              "pt": "Configurações do adaptador",                      "nl": "Adapterinstellingen",                             "fr": "Paramètres de l'adaptateur",                      "it": "Impostazioni dell'adattatore",                    "es": "Ajustes del adaptador",                           "pl": "Ustawienia adaptera"},
    "telegramUser": {                                "en": "Telegram user",                                   "de": "Telegrammbenutzer",                               "ru": "Пользователь Telegram",                           "pt": "Usuário de telegrama",                            "nl": "Telegram-gebruiker",                              "fr": "Utilisateur de télégramme",                       "it": "Utente di Telegram",                              "es": "Usuario de Telegram",                             "pl": "Użytkownik telegramu"},
};