/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'Charge cycle': {                                'en': 'Charge cycle',                                    'de': 'Lade-Zyklus',                                     'ru': 'Цикл зарядки',                                    'pt': 'Ciclo de carga',                                  'nl': 'Laadcyclus',                                      'fr': 'Cycle de Charge',                                 'it': 'Ciclo di carica',                                 'es': 'Ciclo de carga',                                  'pl': 'Cykl ładowania',                                  'zh-cn': '充电周期'},
	'Continuous current': {                          'en': 'Continuous current',                              'de': 'Dauerstrom',                                      'ru': 'Постоянный ток',                                  'pt': 'Corrente contínua',                               'nl': 'Continue stroom',                                 'fr': 'Courant continu',                                 'it': 'Corrente continua',                               'es': 'Corriente continua',                              'pl': 'Prąd stały',                                      'zh-cn': '连续的电流'},
	'room': {                                        'en': 'Room',                                            'de': 'Zimmer',                                          'ru': 'Номер',                                           'pt': 'Quarto',                                          'nl': 'Kamer',                                           'fr': 'Chambre',                                         'it': 'Camera',                                          'es': 'Habitación',                                      'pl': 'Pokój',                                           'zh-cn': '房间'},
	'Warning activated': {                           'en': 'Telegram Warning activated',                      'de': 'Telegramm Warnung aktiviert',                     'ru': 'Предупреждение телеграмму активирован',           'pt': 'Telegrama de Aviso activado',                     'nl': 'Telegram Waarschuwing geactiveerd',               'fr': "Télégramme d'Avertissement activé",               'it': 'Telegramma di Avviso attivato',                   'es': 'Telegrama de Aviso activado',                     'pl': 'Ostrzeżenie telegram aktywowany',                 'zh-cn': '电报警告激活'},
	'Warning deactivated': {                         'en': 'Telegram Warning deactivated',                    'de': 'Telegramm Warnung deaktiviert',                   'ru': 'Предупреждение телеграмма отключены',             'pt': 'Telegrama de Aviso desativados',                  'nl': 'Telegram Waarschuwing uitgeschakeld',             'fr': "Télégramme d'Avertissement désactivé",            'it': 'Telegramma di Avviso disattivato',                'es': 'Telegrama de Aviso desactivado',                  'pl': 'Ostrzeżenie telegram wyłączone',                  'zh-cn': '电报警告停用'},
	'add Device': {                                  'en': 'add Device',                                      'de': 'Gerät hinzufügen',                                'ru': 'добавить устройство',                             'pt': 'adicionar Dispositivo',                           'nl': 'Apparaat toevoegen',                              'fr': 'ajouter un Périphérique',                         'it': 'aggiungi Dispositivo',                            'es': 'añadir Dispositivo',                              'pl': 'dodaj urządzenie',                                'zh-cn': '添加设备'},
	'add User': {                                    'en': 'Add User',                                        'de': 'Benutzer Hinzufügen',                             'ru': 'Добавить Пользователя',                           'pt': 'Adicionar Usuário',                               'nl': 'Gebruiker Toevoegen',                             'fr': 'Ajouter Un Utilisateur',                          'it': 'Aggiungi Utente',                                 'es': 'Agregar Usuario',                                 'pl': 'Dodaj Użytkownika',                               'zh-cn': '增加用户'},
	'charger': {                                     'en': 'Charger',                                         'de': 'Ladegerät',                                       'ru': 'Зарядное устройство',                             'pt': 'Carregador',                                      'nl': 'Lader',                                           'fr': 'Chargeur',                                        'it': 'Caricabatterie',                                  'es': 'Cargador',                                        'pl': 'Ładowarka',                                       'zh-cn': '充电器'},
	'chargerID': {                                   'en': 'Data point from a charger',                       'de': 'Datenpunkt von einem Ladegerät',                  'ru': 'Точки данных из зарядное устройство',             'pt': 'Ponto de dados a partir de um carregador de',     'nl': 'Gegevens punt van een lader',                     'fr': "Point de données à partir d'un chargeur",         'it': 'Punto dati da un caricabatterie',                 'es': 'Punto de datos desde un cargador',                'pl': 'Punkty danych z ładowarka',                       'zh-cn': '数据点，从一个充电器'},
	'delete': {                                      'en': 'Delete',                                          'de': 'Löschen',                                         'ru': 'Удалить',                                         'pt': 'Apagar',                                          'nl': 'Verwijderen',                                     'fr': 'Supprimer',                                       'it': 'Eliminare',                                       'es': 'Eliminar',                                        'pl': 'Usunąć',                                          'zh-cn': '删除'},
	'fully browser': {                               'en': 'FullyBrowser Admin login',                        'de': 'FullyBrowser Admin-login',                        'ru': 'FullyBrowser админ логин',                        'pt': 'FullyBrowser de login de Admin',                  'nl': 'FullyBrowser Admin login',                        'fr': 'FullyBrowser Admin login',                        'it': 'FullyBrowser Admin login',                        'es': 'FullyBrowser inicio de sesión de Administrador',  'pl': 'FullyBrowser admin login',                        'zh-cn': 'FullyBrowser管理登陆'},
	'interval': {                                    'en': 'Polling interval[sec]',                           'de': 'Abrufintervall[sec]',                             'ru': 'Интервал опроса[сек]',                            'pt': 'Intervalo de sondagem[sec]',                      'nl': 'Polling-interval[sec]',                           'fr': "Intervalle d'interrogation de[sec]",              'it': 'Intervallo di Polling[sec]',                      'es': 'Intervalo de sondeo[sec]',                        'pl': 'Interwał sondowania[s]',                          'zh-cn': '投票时间间隔[仲]'},
	'ip': {                                          'en': 'IP Address',                                      'de': 'Die IP-Adresse',                                  'ru': 'IP-адрес',                                        'pt': 'Endereço IP',                                     'nl': 'IP-Adres',                                        'fr': 'Adresse IP',                                      'it': 'Indirizzo IP',                                    'es': 'Dirección IP',                                    'pl': 'Adres IP',                                        'zh-cn': 'IP地址'},
	'motion detector': {                             'en': 'Optional Motion detector',                        'de': 'Optional Bewegungsmelder',                        'ru': 'Опционально детектор движения ',                  'pt': 'Opcional detector de Movimento',                  'nl': 'Optioneel bewegingsmelder',                       'fr': 'En option détecteur de Mouvement',                'it': 'Opzionale rilevatore di Movimento',               'es': 'Opcional detector de Movimiento',                 'pl': 'Opcjonalnie czujnik ruchu ',                      'zh-cn': '可选运动检测器'},
	'motionID': {                                    'en': 'Motion detector ID',                              'de': 'Bewegungsmelder-ID',                              'ru': 'Идентификатор детектор движения ',                'pt': 'Detector de movimento de IDENTIFICAÇÃO',          'nl': 'Bewegingsmelder-ID',                              'fr': 'Détecteur de mouvement ID',                       'it': 'Rilevatore di movimento ID',                      'es': 'Detector de movimiento de la ID',                 'pl': 'Identyfikator czujnik ruchu ',                    'zh-cn': '运动检测器ID'},
	'name': {                                        'en': 'Tablet name',                                     'de': 'Tablet name',                                     'ru': 'Название планшета ',                              'pt': 'Tablet nome',                                     'nl': 'Tablet naam',                                     'fr': 'Nom de la tablette',                              'it': 'Tavoletta nome',                                  'es': 'Nombre de la tableta',                            'pl': 'Nazwa tabletu ',                                  'zh-cn': '片名'},
	'password': {                                    'en': 'Password',                                        'de': 'Passwort',                                        'ru': 'Пароль',                                          'pt': 'Palavra-passe',                                   'nl': 'Wachtwoord',                                      'fr': 'Mot de passe',                                    'it': 'Password',                                        'es': 'Contraseña',                                      'pl': 'Hasło',                                           'zh-cn': '密码'},
	'polling interval': {                            'en': 'Polling interval',                                'de': 'Abrufintervall',                                  'ru': 'Интервал опроса ',                                'pt': 'Intervalo de sondagem',                           'nl': 'Polling-interval',                                'fr': "Intervalle d'interrogation",                      'it': 'Intervallo di Polling',                           'es': 'Intervalo de sondeo',                             'pl': 'Interwał sondowania ',                            'zh-cn': '投票时间间隔'},
	'port': {                                        'en': 'Port',                                            'de': 'Port',                                            'ru': 'порт',                                            'pt': 'porta',                                           'nl': 'poort',                                           'fr': 'port',                                            'it': 'porta',                                           'es': 'puerto',                                          'pl': 'port',                                            'zh-cn': '口'},
	'power_mode': {                                  'en': 'Charging mode',                                   'de': 'Lademodus',                                     'ru': 'режим питания ',                                  'pt': 'modo de alimentação',                             'nl': 'power mode',                                      'fr': "mode d'alimentation",                             'it': 'modalità di alimentazione',                       'es': 'modo de alimentación',                            'pl': 'tryb zasilania ',                                 'zh-cn': '力模式'},
	'telegram': {                                    'en': 'Optional Telegram',                               'de': 'Optional Telegramm',                              'ru': 'Дополнительный Телеграмму',                       'pt': 'Opcional Telegrama',                              'nl': 'Optioneel Telegram',                              'fr': 'En Option Télégramme',                            'it': 'Opzionale Telegramma',                            'es': 'Opcional Telegrama',                              'pl': 'Artykuł Telegram',                                'zh-cn': '可选择的电报'},
	'telegram-enabled': {                            'en': 'Activate Telegram Warning',                       'de': 'Aktivieren Telegramm Warnung',                    'ru': 'Активировать Телеграмма-Предупреждение',          'pt': 'Activar Telegrama De Aviso',                      'nl': 'Activeren Telegram Waarschuwing',                 'fr': "Activer Télégramme D'Avertissement",              'it': 'Attivare Telegramma Di Avviso',                   'es': 'Activar Telegrama De Aviso',                      'pl': 'Aktywować Telegram-Ostrzeżenie',                  'zh-cn': '激活电报警告'},
	'telegramUser': {                                'en': 'Telegram user',                                   'de': 'Telegramm Benutzer',                              'ru': 'Пользователь телеграмма ',                        'pt': 'Telegrama do usuário',                            'nl': 'Telegram gebruiker',                              'fr': "Télégramme de l'utilisateur",                     'it': 'Telegramma utente',                               'es': 'Telegrama de usuario',                            'pl': 'Użytkownik telegram ',                            'zh-cn': '用户电报'},
	'enabled': {                                     'en': 'enabled',                                         'de': 'aktiviert',                                       'ru': 'включен',                                         'pt': 'habilitado',                                      'nl': 'ingeschakeld',                                    'fr': 'activé',                                          'it': 'abilitato',                                       'es': 'habilitado',                                      'pl': 'włączony',                                        'zh-cn': '启用'},

};