// eslint-disable-next-line no-unused-vars
/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'Manual time': {
		'en': 'Manual time',
		'de': 'Manuelle Zeit',
		'ru': 'Ручное время',
		'pt': 'Tempo manual',
		'nl': 'Handmatige tijd',
		'fr': 'Heure manuelle',
		'it': 'Tempo manuale',
		'es': 'Tiempo manual',
		'pl': 'Czas ręczny',
		'zh-cn': '手动时间'
	},
	'astro time': {
		'en': 'astro time',
		'de': 'Astro-Zeit',
		'ru': 'астро время',
		'pt': 'tempo astro',
		'nl': 'astrotijd',
		'fr': 'astro time',
		'it': 'tempo di astro',
		'es': 'tiempo astro',
		'pl': 'czas astro',
		'zh-cn': '天文时间'
	},
	'astro time day': {
		'en': 'astro time day',
		'de': 'Astro Zeit Tag',
		'ru': 'астро время',
		'pt': 'astro time day',
		'nl': 'astro tijd dag',
		'fr': 'astro time day',
		'it': 'astro time day',
		'es': 'día de astro time',
		'pl': 'dzień czasu astro',
		'zh-cn': '天文时间'
	},
	'astro time night': {
		'en': 'astro time night',
		'de': 'Astro Zeit Nacht',
		'ru': 'звездное время ночи',
		'pt': 'astro time night',
		'nl': 'astrotijd nacht',
		'fr': 'astro time night',
		'it': 'astro tempo notte',
		'es': 'noche de astro',
		'pl': 'noc czasu astro',
		'zh-cn': '天文时间之夜'
	},
	'sunrise': {
		'en': 'sunrise',
		'de': 'Sonnenaufgang',
		'ru': 'Восход',
		'pt': 'nascer do sol',
		'nl': 'zonsopkomst',
		'fr': 'lever du soleil',
		'it': 'Alba',
		'es': 'amanecer',
		'pl': 'wschód słońca',
		'zh-cn': '日出'
	},
	'dawn': {
		'en': 'dawn',
		'de': 'Morgendämmerung',
		'ru': 'рассвет',
		'pt': 'alvorecer',
		'nl': 'dageraad',
		'fr': 'Aube',
		'it': 'alba',
		'es': 'amanecer',
		'pl': 'świt',
		'zh-cn': '黎明'
	},
	'nauticalDawn': {
		'en': 'nautical Dawn',
		'de': 'nautische Morgendämmerung',
		'ru': 'морской рассвет',
		'pt': 'amanhecer náutico',
		'nl': 'nautische dageraad',
		'fr': 'aube nautique',
		'it': 'alba nautica',
		'es': 'amanecer náutico',
		'pl': 'żeglarski świt',
		'zh-cn': '航海黎明'
	},
	'nightEnd': {
		'en': 'nightEnd',
		'de': 'Nachtende',
		'ru': 'NightEnD',
		'pt': 'nightEnd',
		'nl': 'nachtEinde',
		'fr': 'nightEnd',
		'it': 'nightEnd',
		'es': 'noche',
		'pl': 'nightEnd',
		'zh-cn': 'nightEnd'
	},
	'nadir': {
		'en': 'nadir',
		'de': 'Nadir',
		'ru': 'надир',
		'pt': 'nadir',
		'nl': 'nadir',
		'fr': 'nadir',
		'it': 'nadir',
		'es': 'nadir',
		'pl': 'nadir',
		'zh-cn': '天底'
	},
	'night': {
		'en': 'night',
		'de': 'Nacht',
		'ru': 'ночь',
		'pt': 'noite',
		'nl': 'nacht',
		'fr': 'nuit',
		'it': 'notte',
		'es': 'noche',
		'pl': 'noc',
		'zh-cn': '晚'
	},
	'nauticalDusk': {
		'en': 'nautical Dusk',
		'de': 'nautische Abenddämmerung',
		'ru': 'морской Сумерки',
		'pt': 'crepúsculo náutico',
		'nl': 'nautische schemering',
		'fr': 'crépuscule nautique',
		'it': 'Crepuscolo nautico',
		'es': 'anochecer náutico',
		'pl': 'żeglarski zmierzch',
		'zh-cn': '航海黄昏'
	},
	'dusk': {
		'en': 'dusk',
		'de': 'Abenddämmerung',
		'ru': 'смеркаться',
		'pt': 'crepúsculo',
		'nl': 'schemer',
		'fr': 'crépuscule',
		'it': 'crepuscolo',
		'es': 'oscuridad',
		'pl': 'zmierzch',
		'zh-cn': '黄昏'
	},
	'sunset': {
		'en': 'sunset',
		'de': 'Sonnenuntergang',
		'ru': 'закат солнца',
		'pt': 'pôr do sol',
		'nl': 'zonsondergang',
		'fr': 'le coucher du soleil',
		'it': 'tramonto',
		'es': 'puesta de sol',
		'pl': 'zachód słońca',
		'zh-cn': '日落'
	},
	'sunsetStart': {
		'en': 'sunset Start',
		'de': 'Sonnenuntergang Start',
		'ru': 'начало заката',
		'pt': 'pôr do sol',
		'nl': 'zonsondergang Start',
		'fr': 'coucher de soleil',
		'it': 'inizio del tramonto',
		'es': 'puesta de sol Inicio',
		'pl': 'zachód słońca Start',
		'zh-cn': '日落开始'
	},
	'goldenHour': {
		'en': 'Golden Hour',
		'de': 'Goldene Stunde',
		'ru': 'Золотой час',
		'pt': 'Hora dourada',
		'nl': 'Gouden uur',
		'fr': 'Golden Hour',
		'it': "Ora d'oro",
		'es': 'Hora dorada',
		'pl': 'Złota godzina',
		'zh-cn': '黄金时段'
	},
	'solarNoon': {
		'en': 'solar Noon',
		'de': 'Sonnenmittag',
		'ru': 'солнечный полдень',
		'pt': 'meio-dia solar',
		'nl': 'zonne-middag',
		'fr': 'midi solaire',
		'it': 'mezzogiorno solare',
		'es': 'mediodía solar',
		'pl': 'słoneczne południe',
		'zh-cn': '太阳正午'
	},
	'goldenHourEnd': {
		'en': 'Golden hour End',
		'de': 'Goldene Stunde Ende',
		'ru': 'Конец золотого часа',
		'pt': 'Hora de ouro Fim',
		'nl': 'Gouden uur einde',
		'fr': "Fin de l'heure d'or",
		'it': "Fine dell'ora d'oro",
		'es': 'Hora dorada Fin',
		'pl': 'Koniec złotej godziny',
		'zh-cn': '黄金时段结束'
	},
	'sunriseEnd': {
		'en': 'sunrise End',
		'de': 'Sonnenaufgang Ende',
		'ru': 'конец восхода',
		'pt': 'fim do nascer do sol',
		'nl': 'einde van de zonsopgang',
		'fr': 'fin du lever du soleil',
		'it': 'sunrise end',
		'es': 'Fin del amanecer',
		'pl': 'wschód słońca Koniec',
		'zh-cn': '日出结束'
	},
	'Brightness control manually': {
		'en': 'Brightness control manually',
		'de': 'Helligkeitsregelung manuell',
		'ru': 'Ручная регулировка яркости',
		'pt': 'Controle de brilho manualmente',
		'nl': 'Helderheidsregeling handmatig',
		'fr': 'Contrôle de la luminosité manuellement',
		'it': 'Controllo della luminosità manualmente',
		'es': 'Control de brillo manualmente',
		'pl': 'Kontrola jasności ręcznie',
		'zh-cn': '手动亮度控制'
	},
	'Brightness control via config page': {
		'en': 'Brightness control via config page',
		'de': 'Helligkeitsregelung über Konfigurationsseite',
		'ru': 'Управление яркостью через страницу конфигурации',
		'pt': 'Controle de brilho via página de configuração',
		'nl': 'Helderheidsregeling via configuratiepagina',
		'fr': 'Contrôle de la luminosité via la page de configuration',
		'it': 'Controllo della luminosità tramite pagina di configurazione',
		'es': 'Control de brillo a través de la página de configuración',
		'pl': 'Kontrola jasności poprzez stronę konfiguracji',
		'zh-cn': '通过配置页面进行亮度控制'
	},
	'Switch off charging control': {
		'en': 'Switch off charging control',
		'de': 'Ladesteuerung ausschalten',
		'ru': 'Отключить контроль зарядки',
		'pt': 'Desligue o controle de carregamento',
		'nl': 'Schakel het opladen uit',
		'fr': 'Désactiver le contrôle de charge',
		'it': 'Disattiva il controllo di ricarica',
		'es': 'Apague el control de carga',
		'pl': 'Wyłącz kontrolę ładowania',
		'zh-cn': '关闭充电控制'
	},
	'Switch on charging control': {
		'en': 'Switch on charging control',
		'de': 'Ladesteuerung einschalten',
		'ru': 'Включить контроль зарядки',
		'pt': 'Ligue o controle de carregamento',
		'nl': 'Schakel het opladen in',
		'fr': 'Activer le contrôle de charge',
		'it': 'Attiva il controllo di ricarica',
		'es': 'Encienda el control de carga',
		'pl': 'Włącz kontrolę ładowania',
		'zh-cn': '开启充电控制'
	},
	'vis view': {
		'en': 'vis view',
		'de': 'vis view',
		'ru': 'вид зрения',
		'pt': 'vis view',
		'nl': 'vis uitzicht',
		'fr': 'vue vue',
		'it': 'vis view',
		'es': 'vista visual',
		'pl': 'widok',
		'zh-cn': '可见'
	},
	'number of the view in widget 8': {
		'en': 'number of the view in widget 8',
		'de': 'Nummer der Ansicht im Widget 8',
		'ru': 'номер представления в виджете 8',
		'pt': 'número da visualização no widget 8',
		'nl': 'nummer van de weergave in widget 8',
		'fr': 'numéro de la vue dans le widget 8',
		'it': 'numero della vista nel widget 8',
		'es': 'número de la vista en el widget 8',
		'pl': 'numer widoku w widżecie 8',
		'zh-cn': '小部件8中的视图编号'
	},
	'time in (sec)': {
		'en': 'time in (sec)',
		'de': 'Zeit in (Sek.)',
		'ru': 'время в (сек)',
		'pt': 'tempo em (s)',
		'nl': 'tijd in (sec)',
		'fr': 'temps en (sec)',
		'it': 'tempo in (sec)',
		'es': 'tiempo en (seg)',
		'pl': 'czas w sekundach',
		'zh-cn': '时间（秒）'
	},
	'Instance ID from the tablet': {
		'en': 'Instance ID from the tablet',
		'de': 'Instanz-ID vom Tablet',
		'ru': 'ID экземпляра с планшета',
		'pt': 'ID da instância do tablet',
		'nl': 'Instantie-ID van de tablet',
		'fr': "ID d'instance de la tablette",
		'it': 'ID istanza dal tablet',
		'es': 'ID de instancia de la tableta',
		'pl': 'Identyfikator wystąpienia z tabletu',
		'zh-cn': '平板电脑的实例ID'
	},
	'Vis View Name': {
		'en': 'Vis View Name',
		'de': 'Vis View Name',
		'ru': 'Vis View Name',
		'pt': 'Nome da vista visível',
		'nl': 'Vis View Name',
		'fr': 'Vis View Name',
		'it': 'Vis View Name',
		'es': 'Nombre de vista de Vis',
		'pl': 'Vis Wyświetl nazwę',
		'zh-cn': '可见视图名称'
	},
	'add View': {
		'en': 'add View',
		'de': 'Ansicht hinzufügen',
		'ru': 'добавить вид',
		'pt': 'adicionar vista',
		'nl': 'weergave toevoegen',
		'fr': 'ajouter une vue',
		'it': 'aggiungi Visualizza',
		'es': 'agregar vista',
		'pl': 'dodaj Widok',
		'zh-cn': '添加视图'
	},
	'vis Mode widget 8 or vis control': {
		'en': 'vis Mode widget 8 or vis control',
		'de': 'vis Modus Widget 8 oder vis control',
		'ru': 'Виджет Виджет режима 8 или контроль видимости',
		'pt': 'vis Mode widget 8 ou vis control',
		'nl': 'vis Mode widget 8 of vis controle',
		'fr': 'widget mode vis 8 ou contrôle vis',
		'it': 'widget modalità vis 8 o controllo vis',
		'es': 'vis Modo widget 8 o vis control',
		'pl': 'Widżet trybu vis 8 lub kontrola',
		'zh-cn': 'vis Mode小部件8或vis control'
	},
	'Activate view change': {
		'en': 'Activate view change',
		'de': 'Ansichtsänderung aktivieren',
		'ru': 'Активировать изменение вида',
		'pt': 'Ativar alteração de visualização',
		'nl': 'Activeer weergave wijzigen',
		'fr': 'Activer le changement de vue',
		'it': 'Attiva modifica vista',
		'es': 'Activar cambio de vista',
		'pl': 'Aktywuj zmianę widoku',
		'zh-cn': '激活视图更改'
	},
	'Deactivate view change': {
		'en': 'Deactivate view change',
		'de': 'Ansichtsänderung deaktivieren',
		'ru': 'Отключить изменение вида',
		'pt': 'Desativar alteração de exibição',
		'nl': 'Weergave wijzigen deactiveren',
		'fr': 'Désactiver le changement de vue',
		'it': 'Disattiva la modifica della vista',
		'es': 'Desactivar cambio de vista',
		'pl': 'Dezaktywuj zmianę widoku',
		'zh-cn': '停用视图更改'
	},
	'Automatic Vis view change': {
		'en': 'Automatic Vis view change',
		'de': 'Automatische Änderung der Vis-Ansicht',
		'ru': 'Автоматическое изменение вида Vis',
		'pt': 'Alteração automática da visualização Vis',
		'nl': 'Automatische Vis-weergave wijzigen',
		'fr': 'Changement automatique de la vue Vis',
		'it': 'Cambio automatico della vista Vis',
		'es': 'Cambio automático de vista de Vis',
		'pl': 'Automatyczna zmiana widoku Vis',
		'zh-cn': '自动Vis视图更改'
	},
	'18Clock': {
		'en': '18 Clock',
		'de': '18 Uhr',
		'ru': '18 часов',
		'pt': '18 Relógio',
		'nl': '18 Klok',
		'fr': '18 Horloge',
		'it': '18 Orologio',
		'es': '18 reloj',
		'pl': '18 Zegar',
		'zh-cn': '18时钟'
	},
	'19Clock': {
		'en': '19 Clock',
		'de': '19 Uhr',
		'ru': '19 часов',
		'pt': '19 Relógio',
		'nl': '19 Klok',
		'fr': '19 Horloge',
		'it': '19 Orologio',
		'es': '19 reloj',
		'pl': '19 Zegar',
		'zh-cn': '19时钟'
	},
	'20Clock': {
		'en': '20 Clock',
		'de': '20 Uhr',
		'ru': '20 часов',
		'pt': '20 Relógio',
		'nl': '20 Klok',
		'fr': '20 Horloge',
		'it': '20 Orologio',
		'es': '20 reloj',
		'pl': '20 Zegar',
		'zh-cn': '20时钟'
	},
	'21Clock': {
		'en': '21 Clock',
		'de': '21 Uhr',
		'ru': '21 Часы',
		'pt': '21 Relógio',
		'nl': '21 Klok',
		'fr': '21 Horloge',
		'it': '21 Orologio',
		'es': '21 reloj',
		'pl': '21 Zegar',
		'zh-cn': '21时钟'
	},
	'22Clock': {
		'en': '22 Clock',
		'de': '22 Uhr',
		'ru': '22 часов',
		'pt': '22 Relógio',
		'nl': '22 Klok',
		'fr': '22 Horloge',
		'it': '22 Orologio',
		'es': '22 reloj',
		'pl': '22 Zegar',
		'zh-cn': '22时钟'
	},
	'23Clock': {
		'en': '23 Clock',
		'de': '23 Uhr',
		'ru': '23 часов',
		'pt': '23 Relógio',
		'nl': '23 Klok',
		'fr': '23 Horloge',
		'it': '23 Orologio',
		'es': '23 reloj',
		'pl': '23 Zegar',
		'zh-cn': '23时钟'
	},
	'4Clock': {
		'en': '4 Clock',
		'de': '4 Uhr',
		'ru': '4 часа',
		'pt': '4 Relógio',
		'nl': '4 Klok',
		'fr': '4 Horloge',
		'it': '4 orologio',
		'es': '4 reloj',
		'pl': '4 zegar',
		'zh-cn': '4时钟'
	},
	'5Clock': {
		'en': '5 Clock',
		'de': '5 Uhr',
		'ru': '5 часов',
		'pt': '5 Relógio',
		'nl': '5 Klok',
		'fr': '5 Horloge',
		'it': '5 orologio',
		'es': '5 reloj',
		'pl': '5 Zegar',
		'zh-cn': '5时钟'
	},
	'6Clock': {
		'en': '6 Clock',
		'de': '6 Uhr',
		'ru': '6 часов',
		'pt': '6 Relógio',
		'nl': '6 Klok',
		'fr': '6 Horloge',
		'it': '6 Orologio',
		'es': '6 reloj',
		'pl': '6 Zegar',
		'zh-cn': '6钟'
	},
	'7Clock': {
		'en': '7 Clock',
		'de': '7 Uhr',
		'ru': '7 часов',
		'pt': '7 Relógio',
		'nl': '7 Klok',
		'fr': '7 Horloge',
		'it': '7 Orologio',
		'es': '7 reloj',
		'pl': '7 Zegar',
		'zh-cn': '7时钟'
	},
	'8Clock': {
		'en': '8 Clock',
		'de': '8 Uhr',
		'ru': '8 часов',
		'pt': '8 Relógio',
		'nl': '8 Klok',
		'fr': '8 Horloge',
		'it': '8 orologio',
		'es': '8 reloj',
		'pl': '8 Zegar',
		'zh-cn': '8时钟'
	},
	'9Clock': {
		'en': '9 Clock',
		'de': '9 Uhr',
		'ru': '9 часов',
		'pt': '9 Relógio',
		'nl': '9 Klok',
		'fr': '9 Horloge',
		'it': '9 Orologio',
		'es': '9 reloj',
		'pl': '9 Zegar',
		'zh-cn': '9时钟'
	},
	'Activate motion sensors': {
		'en': 'Activate motion sensors',
		'de': 'Bewegungssensoren aktivieren',
		'ru': 'Активировать датчики движения',
		'pt': 'Ativar sensores de movimento',
		'nl': 'Activeer bewegingssensoren',
		'fr': 'Activer les capteurs de mouvement',
		'it': 'Attiva i sensori di movimento',
		'es': 'Activar sensores de movimiento',
		'pl': 'Aktywuj czujniki ruchu',
		'zh-cn': '激活运动传感器'
	},
	'Brings the browser back to the foreground': {
		'en': 'Brings the FullyBrowser back to the foreground (recommended for Amazon Fire Tablet with Alexa)',
		'de': 'Bringt den FullyBrowser wieder in den Vordergrund (empfohlen für Amazon Fire Tablet mit Alexa)',
		'ru': 'Возвращает FullyBrowser обратно на передний план (рекомендуется для Amazon Fire Tablet с Alexa)',
		'pt': 'Retorna o FullyBrowser de volta ao primeiro plano (recomendado para Amazon Fire Tablet com Alexa)',
		'nl': 'Brengt de FullyBrowser terug naar de voorgrond (aanbevolen voor Amazon Fire Tablet met Alexa)',
		'fr': 'Ramène le FullyBrowser au premier plan (recommandé pour Amazon Fire Tablet avec Alexa)',
		'it': 'Riporta in primo piano il browser completo (consigliato per Amazon Fire Tablet con Alexa)',
		'es': 'Trae el FullyBrowser a primer plano (recomendado para Amazon Fire Tablet con Alexa)',
		'pl': 'Przywraca FullyBrowser z powrotem na pierwszy plan (zalecane dla Amazon Fire Tablet z Alexą)',
		'zh-cn': '将FullyBrowser带回前台（建议使用Alexa的Amazon Fire Tablet）'
	},
	'Charge cycle': {
		'en': 'Charge cycle',
		'de': 'Ladezyklus',
		'ru': 'Цикл зарядки',
		'pt': 'Ciclo de carga',
		'nl': 'Laadcyclus',
		'fr': 'Cycle de charge',
		'it': 'Ciclo di carica',
		'es': 'Ciclo de carga',
		'pl': 'Cykl ładowania',
		'zh-cn': '充电周期'
	},
	'interval for the Checked the brightness in minutes': {
		'en': 'interval for the Checked the brightness in minutes',
		'de': 'Intervall für die Überprüfung der Helligkeit in Minuten',
		'ru': 'интервал для проверки яркости в минутах',
		'pt': 'intervalo para a verificação do brilho em minutos',
		'nl': 'interval voor de Gecontroleerde helderheid in minuten',
		'fr': 'intervalle pour la vérification de la luminosité en minutes',
		'it': 'intervallo per la luminosità controllata in minuti',
		'es': 'intervalo para el Comprobado el brillo en minutos',
		'pl': 'interwał dla Sprawdzonej jasności w minutach',
		'zh-cn': '检查亮度的间隔（以分钟为单位）'
	},
	'Continuous current': {
		'en': 'Continuous current',
		'de': 'Dauerstrom',
		'ru': 'Постоянный ток',
		'pt': 'Corrente contínua',
		'nl': 'Continu stroom',
		'fr': 'Courant continu',
		'it': 'Corrente continua',
		'es': 'Corriente continua',
		'pl': 'Prąd ciągły',
		'zh-cn': '持续电流'
	},
	'Daytime brightness': {
		'en': 'Daytime brightness',
		'de': 'Tageshelligkeit',
		'ru': 'Дневная яркость',
		'pt': 'Brilho diurno',
		'nl': 'Helderheid overdag',
		'fr': 'Luminosité diurne',
		'it': 'Luminosità diurna',
		'es': 'Brillo diurno',
		'pl': 'Jasność w ciągu dnia',
		'zh-cn': '白天亮度'
	},
	'Deactivate motion sensors': {
		'en': 'Deactivate motion sensors',
		'de': 'Bewegungssensoren deaktivieren',
		'ru': 'Деактивировать датчики движения',
		'pt': 'Desativar sensores de movimento',
		'nl': 'Schakel bewegingssensoren uit',
		'fr': 'Désactiver les capteurs de mouvement',
		'it': 'Disattiva i sensori di movimento',
		'es': 'Desactivar sensores de movimiento',
		'pl': 'Dezaktywuj czujniki ruchu',
		'zh-cn': '停用运动传感器'
	},
	'Description of the screensaver': {
		'en': 'Description of the screensaver',
		'de': 'Beschreibung des Bildschirmschoners',
		'ru': 'Описание заставки',
		'pt': 'Descrição do protetor de tela',
		'nl': 'Beschrijving van de screensaver',
		'fr': "Description de l'économiseur d'écran",
		'it': 'Descrizione dello screensaver',
		'es': 'Descripción del salvapantallas',
		'pl': 'Opis wygaszacza ekranu',
		'zh-cn': '屏幕保护程序的描述'
	},
	'Night brightness': {
		'en': 'Night brightness',
		'de': 'Nachthelligkeit',
		'ru': 'Ночная яркость',
		'pt': 'Brilho da noite',
		'nl': 'Nachtelijke helderheid',
		'fr': 'Luminosité nocturne',
		'it': 'Luminosità notturna',
		'es': 'Brillo nocturno',
		'pl': 'Nocna jasność',
		'zh-cn': '夜间亮度'
	},
	'Screen auto': {
		'en': 'Turn off screen automatically',
		'de': 'Bildschirm automatisch ausschalten',
		'ru': 'Выключить экран автоматически',
		'pt': 'Desligue a tela automaticamente',
		'nl': 'Schakel het scherm automatisch uit',
		'fr': "Éteindre l'écran automatiquement",
		'it': 'Disattiva automaticamente lo schermo',
		'es': 'Apaga la pantalla automáticamente',
		'pl': 'Wyłącz ekran automatycznie',
		'zh-cn': '自动关闭屏幕'
	},
	'Screen on': {
		'en': 'Screen permanently on',
		'de': 'Bildschirm permanent eingeschaltet',
		'ru': 'Экран постоянно включен',
		'pt': 'Tela permanentemente ligada',
		'nl': 'Scherm permanent aan',
		'fr': 'Écran allumé en permanence',
		'it': 'Schermo permanentemente acceso',
		'es': 'Pantalla permanentemente encendida',
		'pl': 'Ekran włączony na stałe',
		'zh-cn': '屏幕永久显示'
	},
	'Screensaver Mode': {
		'en': 'Screensaver Mode',
		'de': 'Bildschirmschoner Modus',
		'ru': 'Режим заставки',
		'pt': 'Modo de proteção de tela',
		'nl': 'Screensaver-modus',
		'fr': "Mode économiseur d'écran",
		'it': 'Modalità Screensaver',
		'es': 'Modo de salvapantallas',
		'pl': 'Tryb wygaszacza ekranu',
		'zh-cn': '屏保模式'
	},
	'Screensaver off': {
		'en': 'Screensaver off',
		'de': 'Bildschirmschoner aus',
		'ru': 'Заставка выключена',
		'pt': 'Protetor de tela desativado',
		'nl': 'Screensaver uit',
		'fr': "Économiseur d'écran désactivé",
		'it': 'Salvaschermo disattivato',
		'es': 'Salvapantallas desactivado',
		'pl': 'Wygaszacz ekranu wyłączony',
		'zh-cn': '屏幕保护程序关闭'
	},
	'Screensaver on': {
		'en': 'Screensaver on',
		'de': 'Bildschirmschoner an',
		'ru': 'Заставка включена',
		'pt': 'Protetor de tela ativado',
		'nl': 'Screensaver aan',
		'fr': 'Écran de veille activé',
		'it': 'Salvaschermo attivo',
		'es': 'Salvapantallas activado',
		'pl': 'Wygaszacz ekranu włączony',
		'zh-cn': '屏幕保护程序开启'
	},
	'Url': {
		'en': 'Url',
		'de': 'Url',
		'ru': 'Веб-сайт',
		'pt': 'URL',
		'nl': 'URL',
		'fr': 'URL',
		'it': 'url',
		'es': 'Url',
		'pl': 'URL',
		'zh-cn': '网址'
	},
	'Warning activated': {
		'en': 'Telegram Warning activated',
		'de': 'Telegram Warnung aktiviert',
		'ru': 'Telegram Warning активирован',
		'pt': 'Aviso de Telegrama ativado',
		'nl': 'Telegramwaarschuwing geactiveerd',
		'fr': 'Avertissement télégramme activé',
		'it': 'Avviso telegramma attivato',
		'es': 'Telegram Warning activado',
		'pl': 'Ostrzeżenie telegramu włączone',
		'zh-cn': '电报警告已激活'
	},
	'Warning deactivated': {
		'en': 'Telegram Warning deactivated',
		'de': 'Telegram Warnung deaktiviert',
		'ru': 'Телеграмма Предупреждение деактивировано',
		'pt': 'Aviso de Telegrama desativado',
		'nl': 'Telegramwaarschuwing gedeactiveerd',
		'fr': 'Avertissement de télégramme désactivé',
		'it': 'Avviso telegramma disattivato',
		'es': 'Telegram Warning desactivado',
		'pl': 'Ostrzeżenie telegramu wyłączone',
		'zh-cn': '电报警告已停用'
	},
	'YouTube-Url or wallpaper-Url': {
		'en': 'YouTube-Url or wallpaper-Url',
		'de': 'YouTube-Url oder Wallpaper-Url',
		'ru': 'URL-адрес YouTube или URL-адрес обоев',
		'pt': 'URL do YouTube ou URL do papel de parede',
		'nl': 'YouTube-URL of wallpaper-URL',
		'fr': "YouTube-Url ou fond d'écran-Url",
		'it': 'YouTube-Url o wallpaper-Url',
		'es': 'URL de YouTube o URL de fondo de pantalla',
		'pl': 'Adres URL YouTube lub adres URL tapety',
		'zh-cn': 'YouTube网址或墙纸网址'
	},
	'add Device': {
		'en': 'add Device',
		'de': 'Gerät hinzufügen',
		'ru': 'добавить устройство',
		'pt': 'Adicionar Dispositivo',
		'nl': 'Voeg toestel toe',
		'fr': 'ajouter un appareil',
		'it': 'Aggiungi dispositivo',
		'es': 'añadir dispositivo',
		'pl': 'Dodaj urządzenie',
		'zh-cn': '添加设备'
	},
	'add User': {
		'en': 'add User',
		'de': 'Nutzer hinzufügen',
		'ru': 'Добавить пользователя',
		'pt': 'adicionar usuário',
		'nl': 'Voeg gebruiker toe',
		'fr': 'ajouter un utilisateur',
		'it': 'Aggiungi utente',
		'es': 'agregar usuario',
		'pl': 'Dodaj użytkownika',
		'zh-cn': '添加用户'
	},
	'back to Fully Browser in (min)': {
		'en': 'back to Fully Browser in (min)',
		'de': 'zurück zu Fully Browser in (min)',
		'ru': 'вернуться в полностью браузер в (мин)',
		'pt': 'voltar ao Navegador completo em (min)',
		'nl': 'terug naar Volledig browser in (min)',
		'fr': 'retour au navigateur complet en (min)',
		'it': 'ritorna a Browser completo in (min)',
		'es': 'volver al navegador completo en (min)',
		'pl': 'powrót do w pełni przeglądarki za (min)',
		'zh-cn': '返回到完全浏览器（分钟）'
	},
	'brightness': {
		'en': 'brightness',
		'de': 'Helligkeit',
		'ru': 'яркость',
		'pt': 'brilho',
		'nl': 'helderheid',
		'fr': 'luminosité',
		'it': 'luminosità',
		'es': 'brillo',
		'pl': 'jasność',
		'zh-cn': '亮度'
	},
	'charger': {
		'en': 'charger',
		'de': 'Ladegerät',
		'ru': 'зарядное устройство',
		'pt': 'carregador',
		'nl': 'oplader',
		'fr': 'chargeur',
		'it': 'caricabatterie',
		'es': 'cargador',
		'pl': 'ładowarka',
		'zh-cn': '充电器'
	},
	'chargerID': {
		'en': 'Data point ID from a charger',
		'de': 'Datenpunkt-ID von einem Ladegerät',
		'ru': 'Идентификатор точки данных от зарядного устройства',
		'pt': 'ID do ponto de dados de um carregador',
		'nl': 'Datapunt-ID van een oplader',
		'fr': "ID du point de données d'un chargeur",
		'it': 'ID punto dati da un caricabatterie',
		'es': 'ID del punto de datos de un cargador',
		'pl': 'Identyfikator punktu danych z ładowarki',
		'zh-cn': '来自充电器的数据点ID'
	},
	'dayTime': {
		'en': 'day Time',
		'de': 'Tageszeit',
		'ru': 'Дневное время',
		'pt': 'dia Hora',
		'nl': 'dag Tijd',
		'fr': 'heure du jour',
		'it': 'giorno',
		'es': 'día hora',
		'pl': 'czas dnia',
		'zh-cn': '一天时间'
	},
	'delete': {
		'en': 'delete',
		'de': 'löschen',
		'ru': 'удалять',
		'pt': 'excluir',
		'nl': 'verwijderen',
		'fr': 'supprimer',
		'it': 'Elimina',
		'es': 'Eliminar',
		'pl': 'usunąć',
		'zh-cn': '删除'
	},
	'enabled': {
		'en': 'Enabled',
		'de': 'Aktiviert',
		'ru': 'Включено',
		'pt': 'ativado',
		'nl': 'Ingeschakeld',
		'fr': 'Activée',
		'it': 'Abilitato',
		'es': 'Habilitado',
		'pl': 'Włączone',
		'zh-cn': '已启用'
	},
	'fully browser': {
		'en': 'Browser Admin login',
		'de': 'Browser Admin Login',
		'ru': 'Логин администратора браузера',
		'pt': 'Login do administrador do navegador',
		'nl': 'Browser Admin login',
		'fr': 'Connexion administrateur du navigateur',
		'it': 'Accesso amministratore del browser',
		'es': 'Inicio de sesión de administrador del navegador',
		'pl': 'Logowanie administratora przeglądarki',
		'zh-cn': '浏览器管理员登录'
	},
	'interval': {
		'en': 'Polling interval[sec]',
		'de': 'Abfrageintervall [Sek.]',
		'ru': 'Интервал опроса [сек]',
		'pt': 'Intervalo de pesquisa [seg]',
		'nl': 'Polling-interval [sec]',
		'fr': "Intervalle d'interrogation [sec]",
		'it': 'Intervallo di polling [sec]',
		'es': 'Intervalo de sondeo [seg]',
		'pl': 'Interwał odpytywania [s]',
		'zh-cn': '轮询间隔[秒]'
	},
	'ip': {
		'en': 'IP Address',
		'de': 'IP Adresse',
		'ru': 'Айпи адрес',
		'pt': 'Endereço de IP',
		'nl': 'IP adres',
		'fr': 'Adresse IP',
		'it': 'Indirizzo IP',
		'es': 'Dirección IP',
		'pl': 'Adres IP',
		'zh-cn': 'IP地址'
	},
	'load start': {
		'en': 'Charge start',
		'de': 'Ladestart',
		'ru': 'Начать зарядку',
		'pt': 'Início da cobrança',
		'nl': 'Het opladen begint',
		'fr': 'Début de charge',
		'it': 'Inizio di carica',
		'es': 'Inicio de carga',
		'pl': 'Rozpocznij ładowanie',
		'zh-cn': '充电开始'
	},
	'load stop': {
		'en': 'Charge stop',
		'de': 'Ladestopp',
		'ru': 'Зарядка стоп',
		'pt': 'Parada de carga',
		'nl': 'Laad stop',
		'fr': 'Arrêt de charge',
		'it': 'Stop di carica',
		'es': 'Parada de carga',
		'pl': 'Zatrzymaj ładowanie',
		'zh-cn': '充电停止'
	},
	'minute': {
		'en': 'minute',
		'de': 'Minute',
		'ru': 'минут',
		'pt': 'minuto',
		'nl': 'minuut',
		'fr': 'minute',
		'it': 'minuto',
		'es': 'minuto',
		'pl': 'minuta',
		'zh-cn': '分钟'
	},
	'motion detector': {
		'en': '(Optional) Motion detector',
		'de': '(Optional) Bewegungsmelder',
		'ru': '(Опционально) детектор движения',
		'pt': '(Opcional) Detector de movimento',
		'nl': '(Optioneel) Bewegingsmelder',
		'fr': '(Facultatif) Détecteur de mouvement',
		'it': '(Opzionale) Rilevatore di movimento',
		'es': '(Opcional) Detector de movimiento',
		'pl': '(Opcjonalnie) Detektor ruchu',
		'zh-cn': '（可选）运动探测器'
	},
	'motionID': {
		'en': 'Motion detector ID',
		'de': 'Bewegungsmelder-ID',
		'ru': 'ID детектора движения',
		'pt': 'ID do detector de movimento',
		'nl': 'Bewegingsmelder ID',
		'fr': 'ID du détecteur de mouvement',
		'it': 'ID rilevatore di movimento',
		'es': 'ID del detector de movimiento',
		'pl': 'ID detektora ruchu',
		'zh-cn': '运动探测器ID'
	},
	'name': {
		'en': 'Tablet name',
		'de': 'Tablet Name',
		'ru': 'Название планшета',
		'pt': 'Nome do tablet',
		'nl': 'Tablet naam',
		'fr': 'Nom de la tablette',
		'it': 'Nome del tablet',
		'es': 'Nombre de la tableta',
		'pl': 'Nazwa tabletu',
		'zh-cn': '平板电脑名称'
	},
	'nightTime': {
		'en': 'night Time',
		'de': 'Nachtzeit',
		'ru': 'ночное время',
		'pt': 'período noturno',
		'nl': 'nachttijd',
		'fr': 'la nuit',
		'it': 'notte',
		'es': 'Noche',
		'pl': 'pora nocna',
		'zh-cn': '夜间'
	},
	'password': {
		'en': 'password',
		'de': 'Passwort',
		'ru': 'пароль',
		'pt': 'senha',
		'nl': 'wachtwoord',
		'fr': 'mot de passe',
		'it': "parola d'ordine",
		'es': 'contraseña',
		'pl': 'hasło',
		'zh-cn': '密码'
	},
	'port': {
		'en': 'Port',
		'de': 'Port',
		'ru': 'Port',
		'pt': 'Port',
		'nl': 'Port',
		'fr': 'Port',
		'it': 'Port',
		'es': 'Port',
		'pl': 'Port'
	},
	'power_mode': {
		'en': 'Charging mode',
		'de': 'Lademodus',
		'ru': 'Режим зарядки',
		'pt': 'Modo de carregamento',
		'nl': 'Oplaadmodus',
		'fr': 'Mode de charge',
		'it': 'Modalità di ricarica',
		'es': 'Modo de carga',
		'pl': 'Tryb ładowania',
		'zh-cn': '充电方式'
	},
	'screen': {
		'en': 'screensaver',
		'de': 'Bildschirmschoner',
		'ru': 'экранная заставка',
		'pt': 'protetor de tela',
		'nl': 'screensaver',
		'fr': "économiseur d'écran",
		'it': 'salvaschermo',
		'es': 'salvapantallas',
		'pl': 'wygaszacz ekranu',
		'zh-cn': '屏幕保护'
	},
	'telegram': {
		'en': '(Optional) Telegram',
		'de': '(Optional) Telegram',
		'ru': '(Необязательно) Telegram',
		'pt': '(Opcional) Telegrama',
		'nl': '(Optioneel) Telegram',
		'fr': '(Facultatif) Télégramme',
		'it': '(Opzionale) Telegram',
		'es': '(Opcional) Telegram',
		'pl': '(Opcjonalnie) Telegram',
		'zh-cn': '（可选）电报'
	},
	'telegram-enabled': {
		'en': 'Activate Telegram Warning',
		'de': 'Aktivieren Sie die Telegram Warnung',
		'ru': 'Активировать предупреждение Telegram',
		'pt': 'Ativar aviso de telegrama',
		'nl': 'Activeer Telegram-waarschuwing',
		'fr': "Activer l'avertissement de télégramme",
		'it': "Attiva l'avviso Telegram",
		'es': 'Activar advertencia de telegrama',
		'pl': 'Aktywuj ostrzeżenie telegramu',
		'zh-cn': '激活电报警告'
	},
	'telegramUser': {
		'en': 'Telegram user',
		'de': 'Telegrambenutzer',
		'ru': 'Пользователь Telegram',
		'pt': 'Usuário de telegrama',
		'nl': 'Telegram-gebruiker',
		'fr': 'Utilisateur de télégramme',
		'it': 'Utente di Telegram',
		'es': 'Usuario de Telegram',
		'pl': 'Użytkownik telegramu',
		'zh-cn': '电报用户'
	},
	'lowering when loading': {
		'en': 'lowering when loading',
		'de': 'Absenken beim Laden',
		'ru': 'опускание при погрузке',
		'pt': 'abaixando ao carregar',
		'nl': 'verlagen tijdens het laden',
		'fr': 'abaissement lors du chargement',
		'it': 'abbassamento durante il caricamento',
		'es': 'bajando al cargar',
		'pl': 'opuszczanie podczas ładowania',
		'zh-cn': '加载时降低'
	}
};